export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const REQUEST_FRIENDS_PENDING = 'REQUEST_FRIENDS_PENDING'
export const REQUEST_FRIENDS_SUCCESS = 'REQUEST_FRIENDS_SUCCESS'
export const REQUEST_FRIENDS_FAILED = 'REQUEST_FRIENDS_FAILED'